[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200

[[redirects]]
  from = "/uploads/:key"
  to = "/.netlify/functions/blob/:key"
  status = 200
